server:
  port: 10086

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/jdsend?serverTimezone=Asia/Shanghai
    username: root
    password: 123456

logging:
  level:
    com:
      java:
        jdsend: debug


